### PR TITLE
Adds HPC RSE meetup blog

### PR DESCRIPTION
**Pull request by aturner-epcc**

### CODE REVIEW

**Review by clairbarrass — CHANGES_REQUESTED** [review]
Line 17 has an errant close-square bracket, which means the subsequent link text and link do not display as intended.

**Comment by clairbarrass** [comment]
also line 29  Hardware  (sp)

**Review by clairbarrass — APPROVED** [review]
lgtm

**Comment by aturner-epcc** [comment]
Well spotted, I think I have fixed them now

**Pull request merged**
